# Input libraries

In [669]:
import keras
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [670]:
import torch
torch.cuda.empty_cache()

# Data input

In [671]:
# Importing the dataset
dataset = pd.read_csv('default of credit card clients.csv')


In [672]:
import pandas as pd
from sklearn import preprocessing

# X and Y distribution of dataset

In [673]:
X = dataset.iloc[:, 1:24].values
y = dataset.iloc[:, 24].values
X.shape,y.shape
type(y)

numpy.ndarray

In [674]:
X.shape

(30000, 23)

In [675]:
import pandas as pd
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)
df = pd.DataFrame(X)
df

0    1         2         3         4    5    6    7    8    9   \
0      0.010101  1.0  0.333333  0.333333  0.051724  0.4  0.4  0.1  0.1  0.0   
1      0.111111  1.0  0.333333  0.666667  0.086207  0.1  0.4  0.2  0.2  0.2   
2      0.080808  1.0  0.333333  0.666667  0.224138  0.2  0.2  0.2  0.2  0.2   
3      0.040404  1.0  0.333333  0.333333  0.275862  0.2  0.2  0.2  0.2  0.2   
4      0.040404  0.0  0.333333  0.333333  0.620690  0.1  0.2  0.1  0.2  0.2   
...         ...  ...       ...       ...       ...  ...  ...  ...  ...  ...   
29995  0.212121  0.0  0.500000  0.333333  0.310345  0.2  0.2  0.2  0.2  0.2   
29996  0.141414  0.0  0.500000  0.666667  0.379310  0.1  0.1  0.1  0.1  0.2   
29997  0.020202  0.0  0.333333  0.666667  0.275862  0.6  0.5  0.4  0.1  0.2   
29998  0.070707  0.0  0.500000  0.333333  0.344828  0.3  0.1  0.2  0.2  0.2   
29999  0.040404  0.0  0.333333  0.333333  0.431034  0.2  0.2  0.2  0.2  0.2   

       ...        13        14        15        16        17        18  \
0      ...  0.086723  0.160138  0.080648  0.260979  0.000000  0.000409   
1      ...  0.087817  0.163220  0.084074  0.263485  0.000000  0.000594   
2      ...  0.093789  0.173637  0.095470  0.272928  0.001738  0.000891   
3      ...  0.113407  0.186809  0.109363  0.283685  0.002290  0.001199   
4      ...  0.106020  0.179863  0.099633  0.275681  0.002290  0.021779   
...    ...       ...       ...       ...       ...       ...       ...   
29995  ...  0.200746  0.243036  0.111622  0.273259  0.009730  0.011875   
29996  ...  0.088267  0.168596  0.085794  0.260979  0.002103  0.002094   
29997  ...  0.087859  0.179805  0.101057  0.275854  0.000000  0.000000   
29998  ...  0.128239  0.209850  0.092403  0.298591  0.098334  0.002024   
29999  ...  0.113667  0.194553  0.112803  0.272746  0.002379  0.001069   

             19        20        21        22  
0      0.000000  0.000000  0.000000  0.000000  
1      0.001116  0.001610  0.000000  0.003783  
2      0.001116  0.001610  0.002345  0.009458  
3      0.001339  0.001771  0.002506  0.001892  
4      0.011160  0.014493  0.001615  0.001284  
...         ...       ...       ...       ...  
29995  0.005583  0.004907  0.011723  0.001892  
29996  0.010042  0.000208  0.000000  0.000000  
29997  0.024552  0.006763  0.004689  0.005864  
29998  0.001315  0.003101  0.124174  0.003412  
29999  0.001596  0.001610  0.002345  0.001892  

[30000 rows x 23 columns]

In [676]:
X[1]

array([1.11111111e-01, 1.00000000e+00, 3.33333333e-01, 6.66666667e-01,
       8.62068966e-02, 1.00000000e-01, 4.00000000e-01, 2.00000000e-01,
       2.00000000e-01, 2.00000000e-01, 4.00000000e-01, 1.48892434e-01,
       6.78575089e-02, 8.78171337e-02, 1.63219937e-01, 8.40739510e-02,
       2.63484742e-01, 0.00000000e+00, 5.93732912e-04, 1.11602161e-03,
       1.61030596e-03, 0.00000000e+00, 3.78310691e-03])

In [677]:
X[1]

array([1.11111111e-01, 1.00000000e+00, 3.33333333e-01, 6.66666667e-01,
       8.62068966e-02, 1.00000000e-01, 4.00000000e-01, 2.00000000e-01,
       2.00000000e-01, 2.00000000e-01, 4.00000000e-01, 1.48892434e-01,
       6.78575089e-02, 8.78171337e-02, 1.63219937e-01, 8.40739510e-02,
       2.63484742e-01, 0.00000000e+00, 5.93732912e-04, 1.11602161e-03,
       1.61030596e-03, 0.00000000e+00, 3.78310691e-03])

# Convert Categorical to Numerical Data

In [678]:
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# #for country column
# labelencoder_X_1 = LabelEncoder()
# X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
# #for gender column
# labelencoder_X_2 = LabelEncoder()
# X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
# np.shape(X)
# X

# Deep Learning Baseline Model-Using Buildin Function

In [679]:
# # baseline model(using 1 connected layer and one 1 output layer)
# def create_baseline():
# # create model
#     model = Sequential()
#     model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
#     model.add(Dense(23, input_dim=30, kernel_initializer='normal', activation='relu'))
#     model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
#     model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
#     model.add(Dense(1, kernel_initializer='random_normal', activation='tanh'))
#     # Compile model
#     model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#     return model

In [680]:
# seed = 7
# numpy.random.seed(seed)
# # evaluate model with standardized dataset
# estimator = KerasClassifier(build_fn=create_baseline, epochs=50, batch_size=5, verbose=0)
# kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
# results = cross_val_score(estimator, X, y, cv=kfold)
# print("Results: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))


# Deep Learning Model-Using Sequential Module


In [681]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
X_train

array([[2.02020202e-02, 1.00000000e+00, 3.33333333e-01, ...,
        1.77133655e-03, 3.41125691e-03, 1.46595393e-03],
       [1.31313131e-01, 1.00000000e+00, 1.66666667e-01, ...,
        8.05152979e-03, 1.40670388e-02, 9.45776729e-03],
       [1.91919192e-01, 1.00000000e+00, 3.33333333e-01, ...,
        4.83735910e-03, 7.04758645e-03, 7.58891247e-03],
       ...,
       [1.91919192e-01, 0.00000000e+00, 3.33333333e-01, ...,
        8.05152979e-04, 2.34450647e-03, 2.07287777e-01],
       [1.21212121e-01, 0.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.08080808e-02, 1.00000000e+00, 3.33333333e-01, ...,
        1.77133655e-03, 5.15791423e-03, 2.83733019e-03]])

In [682]:
type(X_train)

numpy.ndarray

In [683]:
X_train

array([[2.02020202e-02, 1.00000000e+00, 3.33333333e-01, ...,
        1.77133655e-03, 3.41125691e-03, 1.46595393e-03],
       [1.31313131e-01, 1.00000000e+00, 1.66666667e-01, ...,
        8.05152979e-03, 1.40670388e-02, 9.45776729e-03],
       [1.91919192e-01, 1.00000000e+00, 3.33333333e-01, ...,
        4.83735910e-03, 7.04758645e-03, 7.58891247e-03],
       ...,
       [1.91919192e-01, 0.00000000e+00, 3.33333333e-01, ...,
        8.05152979e-04, 2.34450647e-03, 2.07287777e-01],
       [1.21212121e-01, 0.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.08080808e-02, 1.00000000e+00, 3.33333333e-01, ...,
        1.77133655e-03, 5.15791423e-03, 2.83733019e-03]])

In [684]:
y.shape

(30000,)

In [685]:
import tensorflow as tf
# import keras
# from keras import layers
# from keras import models
# from keras import utils
# from keras.layers import Dense
# from keras.models import Sequential
# from keras.layers import Flatten
# from keras.layers import Dropout
# from keras.layers import Activation
# from keras.regularizers import l2
# from keras.optimizers import SGD
# from keras.optimizers import RMSprop
# from keras import datasets

# from keras.callbacks import LearningRateScheduler
# from keras.callbacks import History

# from keras import losses
# from sklearn.utils import shuffle
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD
from keras.callbacks import EarlyStopping, ModelCheckpoint
print(tf.__version__)
print(tf.keras.__version__)

2.5.0
2.5.0


In [686]:
lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-2,
    decay_steps=10000,
    decay_rate=0.1)
optimizer1 = keras.optimizers.SGD(learning_rate=lr_schedule)
optimizer2 = keras.optimizers.Adam(learning_rate = 0.001,beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07)

In [687]:
my_callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2),
    tf.keras.callbacks.ModelCheckpoint(filepath='model.{epoch:02d}-{loss:.2f}.h5'),
    tf.keras.callbacks.TensorBoard(log_dir='./logs'),
]

In [688]:
# #Initializing Neural Network
# Model = keras.Sequential()
# Model.add(Dense(100, input_dim = 23, kernel_initializer = 'random_uniform', activation = 'relu'))
# # Adding the second hidden layer
# Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# # Adding the third hidden layer
# Model.add(Dense(300, kernel_initializer = 'uniform', activation = 'relu'))
# # Adding the Fourth hidden layer
# Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# # Adding the Fifth layer
# Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# # Adding the output layer
# Model.add(Dense(1, kernel_initializer = 'random_uniform', activation = 'sigmoid'))
# # Compiling Neural Network
# Model.compile(optimizer = optimizer2, loss = 'binary_crossentropy', metrics = ['accuracy'])
# #fitting the neural Network
# early_stopping_monitor = EarlyStopping(patience=2)
# Model.fit(X_train, y_train, batch_size = 15, epochs = 50)

In [689]:
score = Model.evaluate(X_test, y_test, verbose=1)
print('Accuracy: ', score[1]*100)
print( 'loss:', score[0]*100)

188/188 [==============================] - 1s 2ms/step - loss: 0.4280 - accuracy: 0.8213
Accuracy:  82.13333487510681
loss: 42.79545843601227


In [690]:
# print(optimizer2.get_weights())

# Pytorch Implementation
## Import necessary libraries

In [691]:
import torch
# import keras
import numpy
import pandas
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Process Start

In [692]:
X_train

array([[2.02020202e-02, 1.00000000e+00, 3.33333333e-01, ...,
        1.77133655e-03, 3.41125691e-03, 1.46595393e-03],
       [1.31313131e-01, 1.00000000e+00, 1.66666667e-01, ...,
        8.05152979e-03, 1.40670388e-02, 9.45776729e-03],
       [1.91919192e-01, 1.00000000e+00, 3.33333333e-01, ...,
        4.83735910e-03, 7.04758645e-03, 7.58891247e-03],
       ...,
       [1.91919192e-01, 0.00000000e+00, 3.33333333e-01, ...,
        8.05152979e-04, 2.34450647e-03, 2.07287777e-01],
       [1.21212121e-01, 0.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.08080808e-02, 1.00000000e+00, 3.33333333e-01, ...,
        1.77133655e-03, 5.15791423e-03, 2.83733019e-03]])

In [693]:
y_train

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [694]:
X_test

array([[0.00000000e+00, 1.00000000e+00, 3.33333333e-01, ...,
        8.05152979e-04, 7.03351941e-04, 3.87768459e-04],
       [9.09090909e-02, 1.00000000e+00, 1.66666667e-01, ...,
        9.50080515e-03, 7.26797006e-03, 0.00000000e+00],
       [2.02020202e-02, 1.00000000e+00, 3.33333333e-01, ...,
        9.66183575e-04, 6.89753803e-03, 1.13493207e-03],
       ...,
       [7.07070707e-02, 0.00000000e+00, 1.66666667e-01, ...,
        0.00000000e+00, 9.57730893e-03, 0.00000000e+00],
       [7.07070707e-02, 0.00000000e+00, 3.33333333e-01, ...,
        4.02576490e-03, 7.03351941e-03, 9.45776729e-03],
       [2.02020202e-02, 0.00000000e+00, 1.66666667e-01, ...,
        2.31884058e-04, 3.00096828e-04, 7.37705848e-05]])

In [695]:
y_test

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [696]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [697]:
x_data

tensor([[1, 2],
        [3, 4]])

### Convert to Tensors

In [698]:
# X_train = torch.tensor(X_train)

In [699]:
X_train.shape

(24000, 23)

In [700]:
y_train

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [701]:
y_test

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [702]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import torch.nn.functional as F

## Empty Cache

In [703]:
y_train_tens=y_train.astype(float)
X_test_tens = X_test.astype(float)
y_test_tens = y_test.astype(float)
X_train_tens=X_train.astype(float)
y_train.shape[0]

24000

In [707]:
import torch

# X=X_iris_tr; Y=Y_iris_tr; X_val=X_iris_val; Y_val=Y_iris_val
# del X, Y, X_val, Y_val

def two_layer_regression_autograd_train(X, Y, X_val, Y_val, lr, nite):

    dtype = torch.float
    device = torch.device("cpu")
    # device = torch.device("cuda:0") # Uncomment this to run on GPU

    # N is batch size; D_in is input dimension;
    # H is hidden dimension; D_out is output dimension.
    N, D_in, H, D_out = 100, X.shape[1], 200, Y.shape[0]

    # Setting requires_grad=False indicates that we do not need to compute gradients
    # with respect to these Tensors during the backward pass.
    X = torch.from_numpy(X).float().to(device = device)
    Y = torch.from_numpy(Y).float().to(device = device)
    X_val = torch.from_numpy(X_val).float().to(device = device)
    Y_val = torch.from_numpy(Y_val).float().to(device = device)

    # Create random Tensors for weights.
    # Setting requires_grad=True indicates that we want to compute gradients with
    # respect to these Tensors during the backward pass.
    W1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
    W2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

    losses_tr, losses_val = list(), list()

    learning_rate = lr
    for t in range(nite):
        # Forward pass: compute predicted y using operations on Tensors; these
        # are exactly the same operations we used to compute the forward pass using
        # Tensors, but we do not need to keep references to intermediate values since
        # we are not implementing the backward pass by hand.
        y_pred = X.mm(W1).clamp(min=0).mm(W2)

        # Compute and print loss using operations on Tensors.
        # Now loss is a Tensor of shape (1,)
        # loss.item() gets the scalar value held in the loss.
        loss = (y_pred - Y).pow(2).sum()

        # Use autograd to compute the backward pass. This call will compute the
        # gradient of loss with respect to all Tensors with requires_grad=True.
        # After this call w1.grad and w2.grad will be Tensors holding the gradient
        # of the loss with respect to w1 and w2 respectively.
        loss.backward()

        # Manually update weights using gradient descent. Wrap in torch.no_grad()
        # because weights have requires_grad=True, but we don't need to track this
        # in autograd.
        # An alternative way is to operate on weight.data and weight.grad.data.
        # Recall that tensor.data gives a tensor that shares the storage with
        # tensor, but doesn't track history.
        # You can also use torch.optim.SGD to achieve this.
        with torch.no_grad():
            W1 -= learning_rate * W1.grad
            W2 -= learning_rate * W2.grad

            # Manually zero the gradients after updating weights
            W1.grad.zero_()
            W2.grad.zero_()

            y_pred = X_val.mm(W1).clamp(min=0).mm(W2)

            # Compute and print loss using operations on Tensors.
            # Now loss is a Tensor of shape (1,)
            # loss.item() gets the scalar value held in the loss.
            loss_val = (y_pred - Y).pow(2).sum()

        if t % 10 == 0:
            print(t, loss.item(), loss_val.item())

        losses_tr.append(loss.item())
        losses_val.append(loss_val.item())

    return W1, W2, losses_tr, losses_val

W1, W2, losses_tr, losses_val = two_layer_regression_autograd_train(X=X_train, Y=y_train, X_val=X_test, Y_val=y_test,
                                                                 lr=1e-4, nite=50)
plt.plot(np.arange(len(losses_tr)), losses_tr, "-b", np.arange(len(losses_val)), losses_val, "-r")

RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:79] data. DefaultCPUAllocator: not enough memory: you tried to allocate 2304000000 bytes.

In [493]:
y_train =torch.tensor(y_train_tens,requires_grad = True).to(device=device)
X_test  =torch.tensor(X_test_tens  ,requires_grad = True).to(device=device)
y_test  =torch.tensor(y_test_tens  ,requires_grad = True).to(device=device)
X_train =torch.tensor(X_train_tens,requires_grad = True).to(device=device)
# y_train=y_train.transpose(-1,0)
# X_test = X_test.transpose(-1,0 )
# y_test = y_test.transpose(-1,0 )
# X_train=X_train.transpose(-1,0)

In [494]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

Using cuda device


## Model

In [547]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(23,200)
        self.fc2 = nn.Linear(200,300)
        self.fc3 = nn.Linear(300,1)

        # self.flatten = nn.Flatten()
        # self.linear_relu_stack = nn.Sequential(
        #     nn.Linear(23, 200),
        #     nn.ReLU(),
        #     nn.Linear(200, 1),
        #     # nn.ReLU(),
        #     # nn.Linear(250, 1),
        #     nn.ReLU()
        # )

    def forward(self, x):
        self.x1 = F.relu(self.fc1(x))
        self.x2 = F.relu(self.fc2(self.x1))
        x3 = F.sigmoid(self.fc3(self.x2))
        return x3

    def backward(self,loss,x3):
        d1 = F.mse_loss(loss,x3)
        
        
    
    def train(self, X, l):
        # Forward propagation
        x3 = self.forward(X)

        # Backward propagation and gradient descent
        self.backward(X, l, x3)
    

In [548]:
model = NeuralNetwork().to(device)
param = list(model.parameters())
print(len(list(model.parameters())))
print(param[0].size())

6
torch.Size([200, 23])


In [549]:
model

NeuralNetwork(
  (fc1): Linear(in_features=23, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=300, bias=True)
  (fc3): Linear(in_features=300, out_features=1, bias=True)
)

## Loss Function

In [550]:
logits = model(X_train.float())
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
# y_pred = y_pred.view(1,-1)
# print(loss)

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.20 GiB already allocated; 0 bytes free; 1.30 GiB reserved in total by PyTorch)

In [535]:
criterion = nn.MSELoss()

loss = criterion(y_pred,y_train.float())
loss = loss.float()
loss

tensor(0.2215, device='cuda:0', grad_fn=<MseLossBackward>)

In [536]:
model.zero_grad()     # zeroes the gradient buffers of all parameters

print('fc1.bias.grad before backward')
print(model.fc1.bias.grad)


fc1.bias.grad before backward
None


In [545]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = model(X_train.float())
loss = criterion(output.float(), y_train.float())
loss.backward()
optimizer.step()    # Does the update

RuntimeError: CUDA out of memory. Tried to allocate 28.00 MiB (GPU 0; 2.00 GiB total capacity; 1.20 GiB already allocated; 0 bytes free; 1.30 GiB reserved in total by PyTorch)

In [242]:
print(X_train.size())
print(X_test.size())
print(y_train.size())
print(y_test.size())

torch.Size([24000, 23])
torch.Size([6000, 23])
torch.Size([24000, 1])
torch.Size([6000])


In [243]:
layer1 = nn.Linear(in_features=23, out_features=200,device=device)
hidden1 = layer1(X_train.float())
print(hidden1.size())

torch.Size([24000, 200])


In [244]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 0.2243, -0.2964, -0.1045,  ...,  0.0027, -0.4305, -0.1404],
        [ 0.2262, -0.3016, -0.1059,  ..., -0.0023, -0.4509, -0.1095],
        [ 0.1858, -0.3416, -0.2001,  ..., -0.0284, -0.3508, -0.1391],
        ...,
        [ 0.1000, -0.1960,  0.0037,  ...,  0.1670, -0.3378,  0.1439],
        [ 0.0984, -0.1800,  0.0675,  ...,  0.0438, -0.2134,  0.0036],
        [ 0.1444, -0.1871,  0.0893,  ...,  0.0098, -0.2346, -0.0534]],
       device='cuda:0', grad_fn=<AddmmBackward>)


After ReLU: tensor([[0.2243, 0.0000, 0.0000,  ..., 0.0027, 0.0000, 0.0000],
        [0.2262, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.1858, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.1000, 0.0000, 0.0037,  ..., 0.1670, 0.0000, 0.1439],
        [0.0984, 0.0000, 0.0675,  ..., 0.0438, 0.0000, 0.0036],
        [0.1444, 0.0000, 0.0893,  ..., 0.0098, 0.0000, 0.0000]],
       device='cuda:0', grad_fn=<ReluBackward0>)


In [245]:
seq_modules = nn.Sequential(
    layer1,
    nn.ReLU(),
    nn.Linear
    (
        200,512,
    device=device
    ),
    nn.ReLU(),
    nn.Linear
    (
        512, 256,
    device =device
    ),
    nn.ReLU(),
    nn.Linear
    (
        256,1,device=device
    ),
    nn.Softmax(dim=1))
# input_image = torch.rand(3,28,28)
logits = seq_modules(X_train.float())

In [246]:

y_train = torch.reshape(y_train, (24000, 1))
y_train.size()

torch.Size([24000, 1])

In [247]:
softmax = nn.Softmax(dim=1)
pred_probab = logits
pred_probab.size()
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_probab, y_train.float())
loss

tensor(1.0911, device='cuda:0', grad_fn=<BinaryCrossEntropyWithLogitsBackward>)

In [248]:
y_train

tensor([[0.],
        [0.],
        [0.],
        ...,
        [1.],
        [1.],
        [0.]], device='cuda:0', grad_fn=<ViewBackward>)

In [249]:
pred_probab

tensor([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]], device='cuda:0', grad_fn=<SoftmaxBackward>)

In [235]:
print("Model structure: ", seq_modules, "\n\n")

for name, param in seq_modules.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure:  Sequential(
  (0): Linear(in_features=23, out_features=200, bias=True)
  (1): ReLU()
  (2): Linear(in_features=200, out_features=512, bias=True)
  (3): ReLU()
  (4): Linear(in_features=512, out_features=256, bias=True)
  (5): ReLU()
  (6): Linear(in_features=256, out_features=1, bias=True)
  (7): Softmax(dim=1)
) 


Layer: 0.weight | Size: torch.Size([200, 23]) | Values : tensor([[ 0.0694, -0.1479, -0.1050, -0.0477,  0.1768, -0.1640, -0.2053, -0.2023,
          0.1288, -0.0069,  0.1991,  0.0728, -0.1491,  0.1413, -0.0040,  0.0661,
          0.1873, -0.1845,  0.0394, -0.1164, -0.0935,  0.1874,  0.0176],
        [ 0.2016, -0.0173, -0.1691,  0.0954,  0.0678, -0.1847,  0.1201,  0.2047,
          0.0838,  0.0665, -0.1913,  0.1045,  0.1565,  0.0428,  0.1819,  0.0788,
          0.1851,  0.1662, -0.1455,  0.0979, -0.1358,  0.1750,  0.0926]],
       device='cuda:0', grad_fn=<SliceBackward>) 

Layer: 0.bias | Size: torch.Size([200]) | Values : tensor([0.1192, 0.2022], device='c

In [250]:
inp = torch.eye(5, requires_grad=True)
out = (inp+1).pow(2)
out.backward(torch.ones_like(inp), retain_graph=True)
print("First call\n", inp.grad)
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nSecond call\n", inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nCall after zeroing gradients\n", inp.grad)

First call
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
