# Input libraries

In [12]:
import keras
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Data input

In [13]:
# Importing the dataset
dataset = pd.read_csv('default of credit card clients.csv')


In [14]:
import pandas as pd
from sklearn import preprocessing

# X and Y distribution of dataset

In [15]:
X = dataset.iloc[:, 1:24].values
y = dataset.iloc[:, 24].values
X.shape,y.shape
type(y)

numpy.ndarray

In [16]:
X.shape

(30000, 23)

In [17]:
import pandas as pd
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)
df = pd.DataFrame(X)
df

0    1         2         3         4    5    6    7    8    9   \
0      0.010101  1.0  0.333333  0.333333  0.051724  0.4  0.4  0.1  0.1  0.0   
1      0.111111  1.0  0.333333  0.666667  0.086207  0.1  0.4  0.2  0.2  0.2   
2      0.080808  1.0  0.333333  0.666667  0.224138  0.2  0.2  0.2  0.2  0.2   
3      0.040404  1.0  0.333333  0.333333  0.275862  0.2  0.2  0.2  0.2  0.2   
4      0.040404  0.0  0.333333  0.333333  0.620690  0.1  0.2  0.1  0.2  0.2   
...         ...  ...       ...       ...       ...  ...  ...  ...  ...  ...   
29995  0.212121  0.0  0.500000  0.333333  0.310345  0.2  0.2  0.2  0.2  0.2   
29996  0.141414  0.0  0.500000  0.666667  0.379310  0.1  0.1  0.1  0.1  0.2   
29997  0.020202  0.0  0.333333  0.666667  0.275862  0.6  0.5  0.4  0.1  0.2   
29998  0.070707  0.0  0.500000  0.333333  0.344828  0.3  0.1  0.2  0.2  0.2   
29999  0.040404  0.0  0.333333  0.333333  0.431034  0.2  0.2  0.2  0.2  0.2   

       ...        13        14        15        16        17        18  \
0      ...  0.086723  0.160138  0.080648  0.260979  0.000000  0.000409   
1      ...  0.087817  0.163220  0.084074  0.263485  0.000000  0.000594   
2      ...  0.093789  0.173637  0.095470  0.272928  0.001738  0.000891   
3      ...  0.113407  0.186809  0.109363  0.283685  0.002290  0.001199   
4      ...  0.106020  0.179863  0.099633  0.275681  0.002290  0.021779   
...    ...       ...       ...       ...       ...       ...       ...   
29995  ...  0.200746  0.243036  0.111622  0.273259  0.009730  0.011875   
29996  ...  0.088267  0.168596  0.085794  0.260979  0.002103  0.002094   
29997  ...  0.087859  0.179805  0.101057  0.275854  0.000000  0.000000   
29998  ...  0.128239  0.209850  0.092403  0.298591  0.098334  0.002024   
29999  ...  0.113667  0.194553  0.112803  0.272746  0.002379  0.001069   

             19        20        21        22  
0      0.000000  0.000000  0.000000  0.000000  
1      0.001116  0.001610  0.000000  0.003783  
2      0.001116  0.001610  0.002345  0.009458  
3      0.001339  0.001771  0.002506  0.001892  
4      0.011160  0.014493  0.001615  0.001284  
...         ...       ...       ...       ...  
29995  0.005583  0.004907  0.011723  0.001892  
29996  0.010042  0.000208  0.000000  0.000000  
29997  0.024552  0.006763  0.004689  0.005864  
29998  0.001315  0.003101  0.124174  0.003412  
29999  0.001596  0.001610  0.002345  0.001892  

[30000 rows x 23 columns]

In [18]:
X[1]

array([1.11111111e-01, 1.00000000e+00, 3.33333333e-01, 6.66666667e-01,
       8.62068966e-02, 1.00000000e-01, 4.00000000e-01, 2.00000000e-01,
       2.00000000e-01, 2.00000000e-01, 4.00000000e-01, 1.48892434e-01,
       6.78575089e-02, 8.78171337e-02, 1.63219937e-01, 8.40739510e-02,
       2.63484742e-01, 0.00000000e+00, 5.93732912e-04, 1.11602161e-03,
       1.61030596e-03, 0.00000000e+00, 3.78310691e-03])

In [19]:
X[1]

array([1.11111111e-01, 1.00000000e+00, 3.33333333e-01, 6.66666667e-01,
       8.62068966e-02, 1.00000000e-01, 4.00000000e-01, 2.00000000e-01,
       2.00000000e-01, 2.00000000e-01, 4.00000000e-01, 1.48892434e-01,
       6.78575089e-02, 8.78171337e-02, 1.63219937e-01, 8.40739510e-02,
       2.63484742e-01, 0.00000000e+00, 5.93732912e-04, 1.11602161e-03,
       1.61030596e-03, 0.00000000e+00, 3.78310691e-03])

# Convert Categorical to Numerical Data

In [20]:
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# #for country column
# labelencoder_X_1 = LabelEncoder()
# X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
# #for gender column
# labelencoder_X_2 = LabelEncoder()
# X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
# np.shape(X)
# X

# Deep Learning Baseline Model-Using Buildin Function

In [21]:
# baseline model(using 1 connected layer and one 1 output layer)
def create_baseline():
# create model
    model = Sequential()
    model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
    model.add(Dense(23, input_dim=30, kernel_initializer='normal', activation='relu'))
    model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
    model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='random_normal', activation='tanh'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [22]:
seed = 7
numpy.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasClassifier(build_fn=create_baseline, epochs=50, batch_size=5, verbose=0)
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, y, cv=kfold)
print("Results: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))


# Deep Learning Model-Using Sequential Module


In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
X_train

array([[4.74747475e-01, 0.00000000e+00, 3.33333333e-01, ...,
        1.93236715e-02, 2.93063309e-02, 2.30769522e-02],
       [2.02020202e-01, 1.00000000e+00, 1.66666667e-01, ...,
        9.49436393e-03, 0.00000000e+00, 1.70024174e-01],
       [2.22222222e-01, 1.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 3.53528131e-02, 1.51324277e-02],
       ...,
       [1.91919192e-01, 0.00000000e+00, 3.33333333e-01, ...,
        1.00756844e-02, 1.55511114e-02, 1.15668494e-02],
       [1.91919192e-01, 1.00000000e+00, 3.33333333e-01, ...,
        4.83091787e-03, 7.03351941e-03, 5.67466037e-03],
       [4.04040404e-02, 1.00000000e+00, 5.00000000e-01, ...,
        4.83091787e-04, 4.68901294e-04, 9.45776729e-04]])

In [65]:
type(X_train)

numpy.ndarray

In [66]:
X_train

array([[4.74747475e-01, 0.00000000e+00, 3.33333333e-01, ...,
        1.93236715e-02, 2.93063309e-02, 2.30769522e-02],
       [2.02020202e-01, 1.00000000e+00, 1.66666667e-01, ...,
        9.49436393e-03, 0.00000000e+00, 1.70024174e-01],
       [2.22222222e-01, 1.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 3.53528131e-02, 1.51324277e-02],
       ...,
       [1.91919192e-01, 0.00000000e+00, 3.33333333e-01, ...,
        1.00756844e-02, 1.55511114e-02, 1.15668494e-02],
       [1.91919192e-01, 1.00000000e+00, 3.33333333e-01, ...,
        4.83091787e-03, 7.03351941e-03, 5.67466037e-03],
       [4.04040404e-02, 1.00000000e+00, 5.00000000e-01, ...,
        4.83091787e-04, 4.68901294e-04, 9.45776729e-04]])

In [67]:
y.shape

(30000,)

In [68]:
import tensorflow as tf
# import keras
# from keras import layers
# from keras import models
# from keras import utils
# from keras.layers import Dense
# from keras.models import Sequential
# from keras.layers import Flatten
# from keras.layers import Dropout
# from keras.layers import Activation
# from keras.regularizers import l2
# from keras.optimizers import SGD
# from keras.optimizers import RMSprop
# from keras import datasets

# from keras.callbacks import LearningRateScheduler
# from keras.callbacks import History

# from keras import losses
# from sklearn.utils import shuffle
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD
from keras.callbacks import EarlyStopping, ModelCheckpoint
print(tf.__version__)
print(tf.keras.__version__)

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-2,
    decay_steps=10000,
    decay_rate=0.1)
optimizer1 = keras.optimizers.SGD(learning_rate=lr_schedule)
optimizer2 = keras.optimizers.Adam(learning_rate = 0.001,beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07)

In [ ]:
my_callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2),
    tf.keras.callbacks.ModelCheckpoint(filepath='model.{epoch:02d}-{loss:.2f}.h5'),
    tf.keras.callbacks.TensorBoard(log_dir='./logs'),
]

In [ ]:
#Initializing Neural Network
Model = keras.Sequential()
Model.add(Dense(100, input_dim = 23, kernel_initializer = 'random_uniform', activation = 'relu'))
# Adding the second hidden layer
Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# Adding the third hidden layer
Model.add(Dense(300, kernel_initializer = 'uniform', activation = 'relu'))
# Adding the Fourth hidden layer
Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# Adding the Fifth layer
Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# Adding the output layer
Model.add(Dense(1, kernel_initializer = 'random_uniform', activation = 'sigmoid'))
# Compiling Neural Network
Model.compile(optimizer = optimizer2, loss = 'binary_crossentropy', metrics = ['accuracy'])
#fitting the neural Network
early_stopping_monitor = EarlyStopping(patience=2)
Model.fit(X_train, y_train, batch_size = 15, epochs = 50)

In [ ]:
score = Model.evaluate(X_test, y_test, verbose=1)
print('Accuracy: ', score[1]*100)
print( 'loss:', score[0]*100)

In [ ]:
print(optimizer2.get_weights())

# Pytorch Implementation
## Import necessary libraries

In [69]:
import torch
# import keras
import numpy
import pandas
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Process Start

In [1]:
X_train

NameError: name 'X_train' is not defined

In [2]:
y_train

NameError: name 'y_train' is not defined

In [73]:
X_test

array([[1.01010101e-02, 1.00000000e+00, 1.66666667e-01, ...,
        1.61030596e-03, 1.23860277e-02, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 3.33333333e-01, ...,
        4.49275362e-04, 2.34450647e-03, 1.51324277e-03],
       [4.04040404e-02, 0.00000000e+00, 1.66666667e-01, ...,
        1.93236715e-03, 9.39678193e-03, 8.33607609e-03],
       ...,
       [2.02020202e-02, 0.00000000e+00, 3.33333333e-01, ...,
        1.34460548e-03, 0.00000000e+00, 0.00000000e+00],
       [4.04040404e-02, 1.00000000e+00, 3.33333333e-01, ...,
        2.41545894e-03, 2.81340776e-03, 2.45901949e-03],
       [2.92929293e-01, 1.00000000e+00, 1.66666667e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [74]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [75]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [84]:
x_data

tensor([[1, 2],
        [3, 4]])

### Convert to Tensors

In [85]:
X_train = torch.tensor(X_train)

<ipython-input-85-af21c8a8097d>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train = torch.tensor(X_train)


In [86]:
X_train

tensor([[4.7475e-01, 0.0000e+00, 3.3333e-01,  ..., 1.9324e-02, 2.9306e-02,
         2.3077e-02],
        [2.0202e-01, 1.0000e+00, 1.6667e-01,  ..., 9.4944e-03, 0.0000e+00,
         1.7002e-01],
        [2.2222e-01, 1.0000e+00, 3.3333e-01,  ..., 0.0000e+00, 3.5353e-02,
         1.5132e-02],
        ...,
        [1.9192e-01, 0.0000e+00, 3.3333e-01,  ..., 1.0076e-02, 1.5551e-02,
         1.1567e-02],
        [1.9192e-01, 1.0000e+00, 3.3333e-01,  ..., 4.8309e-03, 7.0335e-03,
         5.6747e-03],
        [4.0404e-02, 1.0000e+00, 5.0000e-01,  ..., 4.8309e-04, 4.6890e-04,
         9.4578e-04]], dtype=torch.float64)

In [87]:
y_train = torch.tensor(y_train)
X_test = torch.tensor(X_test)
y_test = torch.tensor(y_test)

<ipython-input-87-0b2077a32e82>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train = torch.tensor(y_train)
<ipython-input-87-0b2077a32e82>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test = torch.tensor(X_test)
<ipython-input-87-0b2077a32e82>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test = torch.tensor(y_test)


In [88]:
y_train

tensor([0, 0, 0,  ..., 0, 0, 0])

In [89]:
y_test

tensor([0, 0, 0,  ..., 0, 0, 0])

In [3]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

Using cuda device


In [5]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.ReLU()
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [6]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)
