# Input libraries

In [1]:
import keras
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import torch
torch.cuda.empty_cache()

# Data input

In [3]:
# Importing the dataset
dataset = pd.read_csv('default of credit card clients.csv')


In [4]:
import pandas as pd
from sklearn import preprocessing

# X and Y distribution of dataset

In [5]:
X = dataset.iloc[:, 1:24].values
y = dataset.iloc[:, 24].values
X.shape,y.shape
type(y)

numpy.ndarray

In [6]:
X.shape

(30000, 23)

In [7]:
import pandas as pd
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)
df = pd.DataFrame(X)
df

0    1         2   ...        20        21        22
0      0.010101  1.0  0.333333  ...  0.000000  0.000000  0.000000
1      0.111111  1.0  0.333333  ...  0.001610  0.000000  0.003783
2      0.080808  1.0  0.333333  ...  0.001610  0.002345  0.009458
3      0.040404  1.0  0.333333  ...  0.001771  0.002506  0.001892
4      0.040404  0.0  0.333333  ...  0.014493  0.001615  0.001284
...         ...  ...       ...  ...       ...       ...       ...
29995  0.212121  0.0  0.500000  ...  0.004907  0.011723  0.001892
29996  0.141414  0.0  0.500000  ...  0.000208  0.000000  0.000000
29997  0.020202  0.0  0.333333  ...  0.006763  0.004689  0.005864
29998  0.070707  0.0  0.500000  ...  0.003101  0.124174  0.003412
29999  0.040404  0.0  0.333333  ...  0.001610  0.002345  0.001892

[30000 rows x 23 columns]

In [8]:
X[1]

array([1.11111111e-01, 1.00000000e+00, 3.33333333e-01, 6.66666667e-01,
       8.62068966e-02, 1.00000000e-01, 4.00000000e-01, 2.00000000e-01,
       2.00000000e-01, 2.00000000e-01, 4.00000000e-01, 1.48892434e-01,
       6.78575089e-02, 8.78171337e-02, 1.63219937e-01, 8.40739510e-02,
       2.63484742e-01, 0.00000000e+00, 5.93732912e-04, 1.11602161e-03,
       1.61030596e-03, 0.00000000e+00, 3.78310691e-03])

In [9]:
X[1]

array([1.11111111e-01, 1.00000000e+00, 3.33333333e-01, 6.66666667e-01,
       8.62068966e-02, 1.00000000e-01, 4.00000000e-01, 2.00000000e-01,
       2.00000000e-01, 2.00000000e-01, 4.00000000e-01, 1.48892434e-01,
       6.78575089e-02, 8.78171337e-02, 1.63219937e-01, 8.40739510e-02,
       2.63484742e-01, 0.00000000e+00, 5.93732912e-04, 1.11602161e-03,
       1.61030596e-03, 0.00000000e+00, 3.78310691e-03])

# Convert Categorical to Numerical Data

In [10]:
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# #for country column
# labelencoder_X_1 = LabelEncoder()
# X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
# #for gender column
# labelencoder_X_2 = LabelEncoder()
# X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
# np.shape(X)
# X

# Deep Learning Baseline Model-Using Buildin Function

In [11]:
# # baseline model(using 1 connected layer and one 1 output layer)
# def create_baseline():
# # create model
#     model = Sequential()
#     model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
#     model.add(Dense(23, input_dim=30, kernel_initializer='normal', activation='relu'))
#     model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
#     model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
#     model.add(Dense(1, kernel_initializer='random_normal', activation='tanh'))
#     # Compile model
#     model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#     return model

In [12]:
# seed = 7
# numpy.random.seed(seed)
# # evaluate model with standardized dataset
# estimator = KerasClassifier(build_fn=create_baseline, epochs=50, batch_size=5, verbose=0)
# kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
# results = cross_val_score(estimator, X, y, cv=kfold)
# print("Results: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))


# Deep Learning Model-Using Sequential Module


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
X_train

array([[4.04040404e-02, 0.00000000e+00, 3.33333333e-01, ...,
        2.42834138e-03, 2.44297574e-03, 0.00000000e+00],
       [1.21212121e-01, 0.00000000e+00, 3.33333333e-01, ...,
        1.73913043e-03, 0.00000000e+00, 7.37705848e-04],
       [2.42424242e-01, 1.00000000e+00, 3.33333333e-01, ...,
        7.24798712e-03, 6.61150824e-04, 1.95794698e-02],
       ...,
       [8.08080808e-02, 1.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 1.55909680e-03, 0.00000000e+00],
       [3.93939394e-01, 1.00000000e+00, 3.33333333e-01, ...,
        1.99033816e-03, 2.80754650e-02, 4.78563025e-04],
       [1.71717172e-01, 1.00000000e+00, 5.00000000e-01, ...,
        6.37681159e-04, 9.28424562e-04, 7.49055169e-04]])

In [14]:
type(X_train)

numpy.ndarray

In [15]:
X_train

array([[4.04040404e-02, 0.00000000e+00, 3.33333333e-01, ...,
        2.42834138e-03, 2.44297574e-03, 0.00000000e+00],
       [1.21212121e-01, 0.00000000e+00, 3.33333333e-01, ...,
        1.73913043e-03, 0.00000000e+00, 7.37705848e-04],
       [2.42424242e-01, 1.00000000e+00, 3.33333333e-01, ...,
        7.24798712e-03, 6.61150824e-04, 1.95794698e-02],
       ...,
       [8.08080808e-02, 1.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 1.55909680e-03, 0.00000000e+00],
       [3.93939394e-01, 1.00000000e+00, 3.33333333e-01, ...,
        1.99033816e-03, 2.80754650e-02, 4.78563025e-04],
       [1.71717172e-01, 1.00000000e+00, 5.00000000e-01, ...,
        6.37681159e-04, 9.28424562e-04, 7.49055169e-04]])

In [16]:
y.shape

(30000,)

In [17]:
import tensorflow as tf
# import keras
# from keras import layers
# from keras import models
# from keras import utils
# from keras.layers import Dense
# from keras.models import Sequential
# from keras.layers import Flatten
# from keras.layers import Dropout
# from keras.layers import Activation
# from keras.regularizers import l2
# from keras.optimizers import SGD
# from keras.optimizers import RMSprop
# from keras import datasets

# from keras.callbacks import LearningRateScheduler
# from keras.callbacks import History

# from keras import losses
# from sklearn.utils import shuffle
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD
from keras.callbacks import EarlyStopping, ModelCheckpoint
print(tf.__version__)
print(tf.keras.__version__)

2.5.0
2.5.0


In [18]:
lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-2,
    decay_steps=10000,
    decay_rate=0.1)
optimizer1 = keras.optimizers.SGD(learning_rate=lr_schedule)
optimizer2 = keras.optimizers.Adam(learning_rate = 0.001,beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07)

In [19]:
my_callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2),
    tf.keras.callbacks.ModelCheckpoint(filepath='model.{epoch:02d}-{loss:.2f}.h5'),
    tf.keras.callbacks.TensorBoard(log_dir='./logs'),
]

In [20]:
# #Initializing Neural Network
# Model = keras.Sequential()
# Model.add(Dense(100, input_dim = 23, kernel_initializer = 'random_uniform', activation = 'relu'))
# # Adding the second hidden layer
# Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# # Adding the third hidden layer
# Model.add(Dense(300, kernel_initializer = 'uniform', activation = 'relu'))
# # Adding the Fourth hidden layer
# Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# # Adding the Fifth layer
# Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# # Adding the output layer
# Model.add(Dense(1, kernel_initializer = 'random_uniform', activation = 'sigmoid'))
# # Compiling Neural Network
# Model.compile(optimizer = optimizer2, loss = 'binary_crossentropy', metrics = ['accuracy'])
# #fitting the neural Network
# early_stopping_monitor = EarlyStopping(patience=2)
# Model.fit(X_train, y_train, batch_size = 15, epochs = 50)

In [21]:
# score = Model.evaluate(X_test, y_test, verbose=1)
# print('Accuracy: ', score[1]*100)
# print( 'loss:', score[0]*100)

In [22]:
# print(optimizer2.get_weights())

# Pytorch Implementation
## Import necessary libraries

In [23]:
import torch
# import keras
import numpy
import pandas
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Process Start

In [24]:
X_train

array([[4.04040404e-02, 0.00000000e+00, 3.33333333e-01, ...,
        2.42834138e-03, 2.44297574e-03, 0.00000000e+00],
       [1.21212121e-01, 0.00000000e+00, 3.33333333e-01, ...,
        1.73913043e-03, 0.00000000e+00, 7.37705848e-04],
       [2.42424242e-01, 1.00000000e+00, 3.33333333e-01, ...,
        7.24798712e-03, 6.61150824e-04, 1.95794698e-02],
       ...,
       [8.08080808e-02, 1.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 1.55909680e-03, 0.00000000e+00],
       [3.93939394e-01, 1.00000000e+00, 3.33333333e-01, ...,
        1.99033816e-03, 2.80754650e-02, 4.78563025e-04],
       [1.71717172e-01, 1.00000000e+00, 5.00000000e-01, ...,
        6.37681159e-04, 9.28424562e-04, 7.49055169e-04]])

In [25]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
X_test

array([[4.04040404e-02, 0.00000000e+00, 5.00000000e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.21212121e-01, 1.00000000e+00, 1.66666667e-01, ...,
        6.92431562e-04, 3.47033848e-02, 8.13367987e-04],
       [1.71717172e-01, 1.00000000e+00, 1.66666667e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [7.07070707e-02, 0.00000000e+00, 5.00000000e-01, ...,
        0.00000000e+00, 0.00000000e+00, 4.61539044e-03],
       [4.04040404e-02, 0.00000000e+00, 3.33333333e-01, ...,
        4.33977456e-03, 6.86377714e-02, 7.56621383e-06],
       [2.42424242e-01, 1.00000000e+00, 1.66666667e-01, ...,
        0.00000000e+00, 6.91629409e-03, 0.00000000e+00]])

In [27]:
y_test

array([0, 0, 0, ..., 1, 0, 0])

In [28]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [29]:
x_data

tensor([[1, 2],
        [3, 4]])

### Convert to Tensors

In [30]:
# X_train = torch.tensor(X_train)

In [31]:
X_train.shape

(24000, 23)

In [32]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [33]:
y_test

array([0, 0, 0, ..., 1, 0, 0])

In [34]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import torch.nn.functional as F

## Empty Cache

In [35]:
y_train_tens=y_train.astype(float)
X_test_tens = X_test.astype(float)
y_test_tens = y_test.astype(float)
X_train_tens=X_train.astype(float)
y_train.shape[0]

24000

In [36]:
# import torch

# # X=X_iris_tr; Y=Y_iris_tr; X_val=X_iris_val; Y_val=Y_iris_val
# # del X, Y, X_val, Y_val

# def two_layer_regression_autograd_train(X, Y, X_val, Y_val, lr, nite):

#     dtype = torch.float
#     device = torch.device("cpu")
#     # device = torch.device("cuda:0") # Uncomment this to run on GPU

#     # N is batch size; D_in is input dimension;
#     # H is hidden dimension; D_out is output dimension.
#     N, D_in, H, D_out = X.shape[0], X.shape[1], 200, Y.shape[0]

#     # Setting requires_grad=False indicates that we do not need to compute gradients
#     # with respect to these Tensors during the backward pass.
#     X = torch.from_numpy(X).float()
#     Y = torch.from_numpy(Y).float()
#     X_val = torch.from_numpy(X_val).float()
#     Y_val = torch.from_numpy(Y_val).float()

#     # Create random Tensors for weights.
#     # Setting requires_grad=True indicates that we want to compute gradients with
#     # respect to these Tensors during the backward pass.
#     W1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
#     W2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

#     losses_tr, losses_val = list(), list()

#     learning_rate = lr
#     for t in range(nite):
#         # Forward pass: compute predicted y using operations on Tensors; these
#         # are exactly the same operations we used to compute the forward pass using
#         # Tensors, but we do not need to keep references to intermediate values since
#         # we are not implementing the backward pass by hand.
#         y_pred = X.mm(W1).clamp(min=0).mm(W2)

#         # Compute and print loss using operations on Tensors.
#         # Now loss is a Tensor of shape (1,)
#         # loss.item() gets the scalar value held in the loss.
#         loss = (y_pred - Y).pow(2).sum()

#         # Use autograd to compute the backward pass. This call will compute the
#         # gradient of loss with respect to all Tensors with requires_grad=True.
#         # After this call w1.grad and w2.grad will be Tensors holding the gradient
#         # of the loss with respect to w1 and w2 respectively.
#         loss.backward()

#         # Manually update weights using gradient descent. Wrap in torch.no_grad()
#         # because weights have requires_grad=True, but we don't need to track this
#         # in autograd.
#         # An alternative way is to operate on weight.data and weight.grad.data.
#         # Recall that tensor.data gives a tensor that shares the storage with
#         # tensor, but doesn't track history.
#         # You can also use torch.optim.SGD to achieve this.
#         with torch.no_grad():
#             W1 -= learning_rate * W1.grad
#             W2 -= learning_rate * W2.grad

#             # Manually zero the gradients after updating weights
#             W1.grad.zero_()
#             W2.grad.zero_()

#             y_pred = X_val.mm(W1).clamp(min=0).mm(W2)

#             # Compute and print loss using operations on Tensors.
#             # Now loss is a Tensor of shape (1,)
#             # loss.item() gets the scalar value held in the loss.
#             loss_val = (y_pred - Y).pow(2).sum()

#         if t % 10 == 0:
#             print(t, loss.item(), loss_val.item())

#         losses_tr.append(loss.item())
#         losses_val.append(loss_val.item())

#     return W1, W2, losses_tr, losses_val

# W1, W2, losses_tr, losses_val = two_layer_regression_autograd_train(X=X_train, Y=y_train, X_val=X_test, Y_val=y_test,
#                                                                  lr=1e-4, nite=50)
# plt.plot(np.arange(len(losses_tr)), losses_tr, "-b", np.arange(len(losses_val)), losses_val, "-r")

In [37]:
y_train =torch.tensor(y_train_tens,requires_grad = True) 
X_test  =torch.tensor(X_test_tens  ,requires_grad = True)
y_test  =torch.tensor(y_test_tens  ,requires_grad = True)
X_train =torch.tensor(X_train_tens,requires_grad = True) 
print(X_train, y_train.shape[0])

tensor([[4.0404e-02, 0.0000e+00, 3.3333e-01,  ..., 2.4283e-03, 2.4430e-03,
         0.0000e+00],
        [1.2121e-01, 0.0000e+00, 3.3333e-01,  ..., 1.7391e-03, 0.0000e+00,
         7.3771e-04],
        [2.4242e-01, 1.0000e+00, 3.3333e-01,  ..., 7.2480e-03, 6.6115e-04,
         1.9579e-02],
        ...,
        [8.0808e-02, 1.0000e+00, 3.3333e-01,  ..., 0.0000e+00, 1.5591e-03,
         0.0000e+00],
        [3.9394e-01, 1.0000e+00, 3.3333e-01,  ..., 1.9903e-03, 2.8075e-02,
         4.7856e-04],
        [1.7172e-01, 1.0000e+00, 5.0000e-01,  ..., 6.3768e-04, 9.2842e-04,
         7.4906e-04]], dtype=torch.float64, requires_grad=True) 24000


## Complete Sequential Model and Training with SGD Optimizer

In [ ]:
import torch.optim as optim

model = nn.Sequential(nn.Linear(23, 256),
                      nn.ReLU(),
                      nn.Linear(256, 64),
                      nn.ReLU(),
                      nn.Linear(64, 1),
                      nn.LogSoftmax(dim=1))
# Define the loss
criterion = nn.BCELoss()
# Optimizers require the parameters to optimize and a learning rate
optimizer = optim.SGD(model.parameters(), lr=0.003)
epochs = 5
for e in range(epochs):
    running_loss = 0
    for i, x in enumerate(X_train):
        # Flatten MNIST images into a 784 long vector
        x = x.float()
        x = x.view(-1,x.shape[0])
        # Training pass
        optimizer.zero_grad()
        y = y_train.view(y_train.shape[0],1)
        # y = y.type(torch.LongTensor)
        label = y[i].view(1,1)
        # label = torch.full((1,1), y[i], dtype=torch.float)
        label = label.float()
        output = model(x)
        # print(output.shape,label.shape)
        loss = criterion(output, label.detach())
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
    else:
        print(f"Training loss: {running_loss/len(y_train)}")

## Model

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(23,200)
        self.fc2 = nn.Linear(200,300)
        self.fc3 = nn.Linear(300,1)

        # self.flatten = nn.Flatten()
        # self.linear_relu_stack = nn.Sequential(
        #     nn.Linear(23, 200),
        #     nn.ReLU(),
        #     nn.Linear(200, 1),
        #     # nn.ReLU(),
        #     # nn.Linear(250, 1),
        #     nn.ReLU()
        # )

    def forward(self, x):
        self.x1 = F.relu(self.fc1(x))
        self.x2 = F.relu(self.fc2(self.x1))
        x3 = F.sigmoid(self.fc3(self.x2))
        return x3

    

In [ ]:
model = NeuralNetwork().to(device)
param = list(model.parameters())
print(len(list(model.parameters())))
print(param[0].size())

In [ ]:
model

## Loss Function

In [ ]:
logits = model(X_train.float())
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
# y_pred = y_pred.view(1,-1)
# print(loss)

In [ ]:
criterion = nn.MSELoss()

loss = criterion(y_pred,y_train.float())
loss = loss.float()
loss

In [ ]:
model.zero_grad()     # zeroes the gradient buffers of all parameters

print('fc1.bias.grad before backward')
print(model.fc1.bias.grad)


In [ ]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = model(X_train.float())
loss = criterion(output.float(), y_train.float())
loss.backward()
optimizer.step()    # Does the update

In [ ]:
print(X_train.size())
print(X_test.size())
print(y_train.size())
print(y_test.size())

In [ ]:
layer1 = nn.Linear(in_features=23, out_features=200,device=device)
hidden1 = layer1(X_train.float())
print(hidden1.size())

In [ ]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

In [ ]:
seq_modules = nn.Sequential(
    layer1,
    nn.ReLU(),
    nn.Linear
    (
        200,512,
    device=device
    ),
    nn.ReLU(),
    nn.Linear
    (
        512, 256,
    device =device
    ),
    nn.ReLU(),
    nn.Linear
    (
        256,1,device=device
    ),
    nn.Softmax(dim=1))
# input_image = torch.rand(3,28,28)
logits = seq_modules(X_train.float())

In [ ]:

y_train = torch.reshape(y_train, (24000, 1))
y_train.size()

In [ ]:
softmax = nn.Softmax(dim=1)
pred_probab = logits
pred_probab.size()
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_probab, y_train.float())
loss

In [ ]:
y_train

In [ ]:
pred_probab

In [ ]:
print("Model structure: ", seq_modules, "\n\n")

for name, param in seq_modules.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

In [ ]:
inp = torch.eye(5, requires_grad=True)
out = (inp+1).pow(2)
out.backward(torch.ones_like(inp), retain_graph=True)
print("First call\n", inp.grad)
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nSecond call\n", inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nCall after zeroing gradients\n", inp.grad)