# Input libraries

In [237]:
import keras
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Data input

In [238]:
# Importing the dataset
dataset = pd.read_csv('default of credit card clients.csv')


In [239]:
import pandas as pd
from sklearn import preprocessing

# X and Y distribution of dataset

In [240]:
X = dataset.iloc[:, 1:24].values
y = dataset.iloc[:, 24].values
X.shape,y.shape
type(y)

numpy.ndarray

In [241]:
X.shape

(30000, 23)

In [242]:
import pandas as pd
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)
df = pd.DataFrame(x_scaled)
df

0    1         2         3         4    5    6    7    8    9   \
0      0.010101  1.0  0.333333  0.333333  0.051724  0.4  0.4  0.1  0.1  0.0   
1      0.111111  1.0  0.333333  0.666667  0.086207  0.1  0.4  0.2  0.2  0.2   
2      0.080808  1.0  0.333333  0.666667  0.224138  0.2  0.2  0.2  0.2  0.2   
3      0.040404  1.0  0.333333  0.333333  0.275862  0.2  0.2  0.2  0.2  0.2   
4      0.040404  0.0  0.333333  0.333333  0.620690  0.1  0.2  0.1  0.2  0.2   
...         ...  ...       ...       ...       ...  ...  ...  ...  ...  ...   
29995  0.212121  0.0  0.500000  0.333333  0.310345  0.2  0.2  0.2  0.2  0.2   
29996  0.141414  0.0  0.500000  0.666667  0.379310  0.1  0.1  0.1  0.1  0.2   
29997  0.020202  0.0  0.333333  0.666667  0.275862  0.6  0.5  0.4  0.1  0.2   
29998  0.070707  0.0  0.500000  0.333333  0.344828  0.3  0.1  0.2  0.2  0.2   
29999  0.040404  0.0  0.333333  0.333333  0.431034  0.2  0.2  0.2  0.2  0.2   

       ...        13        14        15        16        17        18  \
0      ...  0.086723  0.160138  0.080648  0.260979  0.000000  0.000409   
1      ...  0.087817  0.163220  0.084074  0.263485  0.000000  0.000594   
2      ...  0.093789  0.173637  0.095470  0.272928  0.001738  0.000891   
3      ...  0.113407  0.186809  0.109363  0.283685  0.002290  0.001199   
4      ...  0.106020  0.179863  0.099633  0.275681  0.002290  0.021779   
...    ...       ...       ...       ...       ...       ...       ...   
29995  ...  0.200746  0.243036  0.111622  0.273259  0.009730  0.011875   
29996  ...  0.088267  0.168596  0.085794  0.260979  0.002103  0.002094   
29997  ...  0.087859  0.179805  0.101057  0.275854  0.000000  0.000000   
29998  ...  0.128239  0.209850  0.092403  0.298591  0.098334  0.002024   
29999  ...  0.113667  0.194553  0.112803  0.272746  0.002379  0.001069   

             19        20        21        22  
0      0.000000  0.000000  0.000000  0.000000  
1      0.001116  0.001610  0.000000  0.003783  
2      0.001116  0.001610  0.002345  0.009458  
3      0.001339  0.001771  0.002506  0.001892  
4      0.011160  0.014493  0.001615  0.001284  
...         ...       ...       ...       ...  
29995  0.005583  0.004907  0.011723  0.001892  
29996  0.010042  0.000208  0.000000  0.000000  
29997  0.024552  0.006763  0.004689  0.005864  
29998  0.001315  0.003101  0.124174  0.003412  
29999  0.001596  0.001610  0.002345  0.001892  

[30000 rows x 23 columns]

In [243]:
X[1]

array([1.11111111e-01, 1.00000000e+00, 3.33333333e-01, 6.66666667e-01,
       8.62068966e-02, 1.00000000e-01, 4.00000000e-01, 2.00000000e-01,
       2.00000000e-01, 2.00000000e-01, 4.00000000e-01, 1.48892434e-01,
       6.78575089e-02, 8.78171337e-02, 1.63219937e-01, 8.40739510e-02,
       2.63484742e-01, 0.00000000e+00, 5.93732912e-04, 1.11602161e-03,
       1.61030596e-03, 0.00000000e+00, 3.78310691e-03])

In [244]:
X[1]

array([1.11111111e-01, 1.00000000e+00, 3.33333333e-01, 6.66666667e-01,
       8.62068966e-02, 1.00000000e-01, 4.00000000e-01, 2.00000000e-01,
       2.00000000e-01, 2.00000000e-01, 4.00000000e-01, 1.48892434e-01,
       6.78575089e-02, 8.78171337e-02, 1.63219937e-01, 8.40739510e-02,
       2.63484742e-01, 0.00000000e+00, 5.93732912e-04, 1.11602161e-03,
       1.61030596e-03, 0.00000000e+00, 3.78310691e-03])

# Convert Categorical to Numerical Data

In [245]:
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# #for country column
# labelencoder_X_1 = LabelEncoder()
# X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
# #for gender column
# labelencoder_X_2 = LabelEncoder()
# X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
# np.shape(X)
# X

# Deep Learning Baseline Model-Using Buildin Function

In [246]:
# baseline model(using 1 connected layer and one 1 output layer)
def create_baseline():
# create model
    model = Sequential()
    model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
    model.add(Dense(23, input_dim=30, kernel_initializer='normal', activation='relu'))
    model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
    model.add(Dense(30, input_dim=23, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='random_normal', activation='tanh'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [247]:
seed = 7
numpy.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasClassifier(build_fn=create_baseline, epochs=50, batch_size=5, verbose=0)
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, y, cv=kfold)
print("Results: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))


KeyboardInterrupt: 

# Deep Learning Model-Using Sequential Module


In [290]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
X_train

array([[0.34343434, 1.        , 0.16666667, ..., 0.02333977, 0.12726919,
        0.01267719],
       [0.04040404, 0.        , 0.33333333, ..., 0.00111272, 0.00234451,
        0.00151324],
       [0.19191919, 1.        , 0.5       , ..., 0.01127214, 0.01172253,
        0.00945777],
       ...,
       [0.13131313, 0.        , 0.16666667, ..., 0.        , 0.        ,
        0.        ],
       [0.01010101, 0.        , 0.33333333, ..., 0.00161031, 0.00137154,
        0.00189155],
       [0.04040404, 1.        , 0.33333333, ..., 0.00563607, 0.00820577,
        0.00302649]])

In [291]:
type(X_train)

numpy.ndarray

In [292]:
X_train

array([[0.34343434, 1.        , 0.16666667, ..., 0.02333977, 0.12726919,
        0.01267719],
       [0.04040404, 0.        , 0.33333333, ..., 0.00111272, 0.00234451,
        0.00151324],
       [0.19191919, 1.        , 0.5       , ..., 0.01127214, 0.01172253,
        0.00945777],
       ...,
       [0.13131313, 0.        , 0.16666667, ..., 0.        , 0.        ,
        0.        ],
       [0.01010101, 0.        , 0.33333333, ..., 0.00161031, 0.00137154,
        0.00189155],
       [0.04040404, 1.        , 0.33333333, ..., 0.00563607, 0.00820577,
        0.00302649]])

In [293]:
y.shape

(30000,)

In [294]:
# import tensorflow as tf
# import keras
# from keras import layers
# from keras import models
# from keras import utils
# from keras.layers import Dense
# from keras.models import Sequential
# from keras.layers import Flatten
# from keras.layers import Dropout
# from keras.layers import Activation
# from keras.regularizers import l2
# from keras.optimizers import SGD
# from keras.optimizers import RMSprop
# from keras import datasets

# from keras.callbacks import LearningRateScheduler
# from keras.callbacks import History

# from keras import losses
# from sklearn.utils import shuffle
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD
from keras.callbacks import EarlyStopping, ModelCheckpoint
print(tf.__version__)
print(tf.keras.__version__)

2.5.0
2.5.0


In [295]:
lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-2,
    decay_steps=10000,
    decay_rate=0.1)
optimizer1 = keras.optimizers.SGD(learning_rate=lr_schedule)
optimizer2 = keras.optimizers.Adam(learning_rate = 0.01)

In [296]:
my_callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2),
    tf.keras.callbacks.ModelCheckpoint(filepath='model.{epoch:02d}-{loss:.2f}.h5'),
    tf.keras.callbacks.TensorBoard(log_dir='./logs'),
]

In [297]:
#Initializing Neural Network
Model = keras.Sequential()
Model.add(Dense(100, input_dim = 23, kernel_initializer = 'random_uniform', activation = 'relu'))
# Adding the second hidden layer
Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# Adding the third hidden layer
Model.add(Dense(300, kernel_initializer = 'uniform', activation = 'relu'))
# Adding the Fourth hidden layer
Model.add(Dense(200, kernel_initializer = 'random_uniform', activation = 'relu'))
# Adding the output layer
Model.add(Dense(1, kernel_initializer = 'random_uniform', activation = 'sigmoid'))
# Compiling Neural Network
Model.compile(optimizer = optimizer2, loss = 'binary_crossentropy', metrics = ['accuracy'])
#fitting the neural Network
early_stopping_monitor = EarlyStopping(patience=2)
Model.fit(X_train, y_train, batch_size = 5, epochs = 50)

Epoch 1/50
4800/4800 [==============================] - 10s 2ms/step - loss: 0.4878 - accuracy: 0.7926
Epoch 2/50
4800/4800 [==============================] - 9s 2ms/step - loss: 0.4694 - accuracy: 0.8028
Epoch 3/50
4800/4800 [==============================] - 10s 2ms/step - loss: 0.4613 - accuracy: 0.8083
Epoch 4/50
4800/4800 [==============================] - 9s 2ms/step - loss: 0.4575 - accuracy: 0.8115
Epoch 5/50
4800/4800 [==============================] - 10s 2ms/step - loss: 0.4597 - accuracy: 0.8087
Epoch 6/50
4800/4800 [==============================] - 10s 2ms/step - loss: 0.4545 - accuracy: 0.8111
Epoch 7/50
4800/4800 [==============================] - 9s 2ms/step - loss: 0.4531 - accuracy: 0.8141
Epoch 8/50
4800/4800 [==============================] - 10s 2ms/step - loss: 0.4523 - accuracy: 0.8136
Epoch 9/50
4800/4800 [==============================] - 9s 2ms/step - loss: 0.4530 - accuracy: 0.8148
Epoch 10/50
4800/4800 [==============================] - 10s 2ms/step - loss:

In [298]:
score = Model.evaluate(X_test, y_test, verbose=1)
print('Accuracy: ', score[1]*100)
print( 'loss:', score[0]*100)

188/188 [==============================] - 0s 1ms/step - loss: 0.4425 - accuracy: 0.8130
Accuracy:  81.30000233650208
loss: 44.25054490566254


In [299]:
print(optimizer2.get_weights())

[240000, array([[ 1.1616160e-37,  1.0587055e-37,  1.1367075e-37, ...,
         1.1436810e-37,  1.1011645e-37,  1.0726497e-37],
       [ 0.0000000e+00,  0.0000000e+00,  1.0999606e-37, ...,
         1.1396685e-37,  1.0972972e-37,  1.1254006e-37],
       [ 1.1328309e-37,  1.1654273e-37,  1.1466868e-37, ...,
         1.0644502e-37,  1.0698287e-37,  1.1246911e-37],
       ...,
       [ 1.1208853e-37,  1.0626201e-37,  1.1560830e-37, ...,
         1.1269845e-37,  1.0597427e-37,  0.0000000e+00],
       [ 1.0662006e-37,  1.1562454e-37,  1.0755542e-37, ...,
         1.1484442e-37,  1.1501106e-37,  1.0864880e-37],
       [ 1.0914205e-37,  1.1155625e-37,  1.1117529e-37, ...,
        -1.1534162e-37,  1.1734016e-37,  0.0000000e+00]], dtype=float32), array([ 1.0664832e-37,  1.1536083e-37,  1.0586387e-37,  1.1732489e-37,
        1.1066899e-37,  1.1107275e-37,  1.0865516e-37,  1.1530246e-37,
        1.1618991e-37, -1.0732343e-02,  1.1519771e-37,  1.0590384e-37,
        1.0823827e-37,  1.1453389e-37,  1